### ISSUE TITLE
aws_iam_policy_document data source will trigger json error

### ISSUE THREAD

**Issue by DragonZ** [uber/astro#7] opened 2018-10-31 17:56 UTC
While using `aws_iam_policy_document` data source to generate IAM policy in JSON, `astro` will throw out an error `* invalid character '$' looking for beginning of value`. But the underneath `terraform plan` succeeds without error.

**Comment by dansimau** [comment] 2019-04-17 07:28
Dupe of #5.

**Closed by dansimau** 2019-04-17 07:28 UTC
